using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace SimpleDb.SourceGenerator;

/// <summary>
/// SimpleDb AOT 源代码生成器
/// </summary>
[Generator(LanguageNames.CSharp)]
public class SimpleDbSourceGenerator : IIncrementalGenerator
{
    /// <summary>
    /// 初始化生成器
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 查找所有类声明
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassInfo(ctx))
            .Where(static m => m is not null && ShouldGenerateMapper(m))
            .Collect();

        // 注册源代码生成
        context.RegisterSourceOutput(classDeclarations, static (spc, classes) =>
        {
            if (classes.IsDefaultOrEmpty) return;

            foreach (var classInfo in classes)
            {
                if (classInfo == null) continue;

                var sourceCode = GenerateMapperClass(classInfo);
                var fileName = $"{classInfo.FullName.Replace(".", "_")}_Mapper.g.cs";
                spc.AddSource(fileName, SourceText.From(sourceCode, Encoding.UTF8));
            }
        });
    }

    /// <summary>
    /// 获取类信息
    /// </summary>
    private static ClassInfo? GetClassInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        // 获取类的完整名称
        var namespaceDeclaration = classDeclaration.FirstAncestorOrSelf<NamespaceDeclarationSyntax>();
        var namespaceName = namespaceDeclaration?.Name.ToString() ?? string.Empty;
        var className = classDeclaration.Identifier.Text;

        // 获取属性信息
        var properties = new List<PropertyInfo>();
        foreach (var member in classDeclaration.Members)
        {
            if (member is PropertyDeclarationSyntax property)
            {
                var propertyName = property.Identifier.Text;
                var propertyType = property.Type.ToString();
                properties.Add(new PropertyInfo(propertyName, propertyType));
            }
        }

        return new ClassInfo(namespaceName, className, properties);
    }

    /// <summary>
    /// 判断是否应该为类生成映射器
    /// </summary>
    private static bool ShouldGenerateMapper(ClassInfo classInfo)
    {
        // 排除所有SimpleDb内部命名空间
        if (!string.IsNullOrEmpty(classInfo.Namespace) &&
            (classInfo.Namespace.Contains("SimpleDb") ||
             classInfo.Namespace.Contains("System")))
        {
            return false;
        }

        // 排除所有内部类型的类名
        var excludePatterns = new[]
        {
            "ObjectSerializer", "Serializer", "Mapper", "Query", "Bson", "Cache", "Page",
            "Index", "Lock", "Transaction", "Engine", "Collection", "Stream",
            "BinaryExpression", "ConstantExpression", "MemberExpression",
            "ParameterExpression", "PropertyAccessor", "BTreeNode", "DatabaseStatistics",
            "SimpleDbOptions", "InsertResult", "BTreeNodeStatistics",
            "SimpleDbEntityAttribute", "SimpleDbIdAttribute", "SimpleDbQueryBuilderAttribute"
        };

        if (excludePatterns.Any(pattern => classInfo.Name.Contains(pattern)))
        {
            return false;
        }

        // 排除编译生成的类
        if (classInfo.Name.StartsWith("<") || classInfo.Name.Contains("Anonymous"))
        {
            return false;
        }

        // 只为有属性的类生成映射器
        return classInfo.Properties.Count > 0;
    }

    /// <summary>
    /// 生成映射器类
    /// </summary>
    private static string GenerateMapperClass(ClassInfo classInfo)
    {
        var sb = new StringBuilder();

        // 添加文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using SimpleDb.Bson;");
        sb.AppendLine("using System;");
        sb.AppendLine();

        // 添加命名空间
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"namespace {classInfo.Namespace}");
            sb.AppendLine("{");
        }

        // 添加类
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {classInfo.Name} 的 BSON 映射器");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static partial class {classInfo.Name}Mapper");
        sb.AppendLine("    {");

        // 生成 ToDocument 方法
        GenerateToDocumentMethod(sb, classInfo);

        // 生成 FromDocument 方法
        GenerateFromDocumentMethod(sb, classInfo);

        sb.AppendLine("    }");

        // 关闭命名空间
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 生成 ToDocument 方法
    /// </summary>
    private static void GenerateToDocumentMethod(StringBuilder sb, ClassInfo classInfo)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 将 {classInfo.Name} 转换为 BSON 文档");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        /// <param name=\"entity\">{classInfo.Name} 实体</param>");
        sb.AppendLine("        /// <returns>BSON 文档</returns>");
        sb.AppendLine($"        public static BsonDocument ToDocument(this {classInfo.FullName} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (entity == null) return new BsonDocument();");
        sb.AppendLine();
        sb.AppendLine("            var doc = new BsonDocument();");

        foreach (var property in classInfo.Properties)
        {
            sb.AppendLine($"            doc[\"{property.Name}\"] = ConvertToBsonValue(entity.{property.Name});");
        }

        sb.AppendLine("            return doc;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 FromDocument 方法
    /// </summary>
    private static void GenerateFromDocumentMethod(StringBuilder sb, ClassInfo classInfo)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 从 BSON 文档创建 {classInfo.Name}");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"doc\">BSON 文档</param>");
        sb.AppendLine($"        /// <returns>{classInfo.Name} 实体</returns>");
        sb.AppendLine($"        public static {classInfo.FullName}? FromDocument(this BsonDocument doc)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (doc == null) return null;");
        sb.AppendLine();
        sb.AppendLine($"            var entity = new {classInfo.FullName}();");

        foreach (var property in classInfo.Properties)
        {
            sb.AppendLine($"            if (doc.ContainsKey(\"{property.Name}\"))");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                entity.{property.Name} = ConvertFromBsonValue<{property.Type}>(doc[\"{property.Name}\"]);");
            sb.AppendLine($"            }}");
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 转换为 BSON 值");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"value\">值</param>");
        sb.AppendLine("        /// <returns>BSON 值</returns>");
        sb.AppendLine("        private static BsonValue ConvertToBsonValue(object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            return value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                null => BsonNull.Value,");
        sb.AppendLine("                string s => s,");
        sb.AppendLine("                int i => i,");
        sb.AppendLine("                long l => l,");
        sb.AppendLine("                double d => d,");
        sb.AppendLine("                bool b => b,");
        sb.AppendLine("                DateTime dt => dt,");
        sb.AppendLine("                ObjectId id => id,");
        sb.AppendLine("                _ => BsonNull.Value");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 从 BSON 值转换");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">目标类型</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">BSON 值</param>");
        sb.AppendLine("        /// <returns>转换后的值</returns>");
        sb.AppendLine("        private static T ConvertFromBsonValue<T>(BsonValue value)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value == null || value.IsNull) return default(T)!;");
        sb.AppendLine();
        sb.AppendLine("            return typeof(T).Name switch");
        sb.AppendLine("            {");
        sb.AppendLine("                \"String\" => (T)(object)value.AsString,");
        sb.AppendLine("                \"Int32\" => (T)(object)value.AsInt32,");
        sb.AppendLine("                \"Int64\" => (T)(object)value.AsInt64,");
        sb.AppendLine("                \"Double\" => (T)(object)value.AsDouble,");
        sb.AppendLine("                \"Boolean\" => (T)(object)value.AsBoolean,");
        sb.AppendLine("                \"DateTime\" => (T)(object)value.AsDateTime,");
        sb.AppendLine("                \"ObjectId\" => (T)(object)value.AsObjectId,");
        sb.AppendLine("                _ => default(T)!");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }
}

/// <summary>
/// 类信息
/// </summary>
public class ClassInfo
{
    public string Namespace { get; }
    public string Name { get; }
    public string FullName => string.IsNullOrEmpty(Namespace) ? Name : $"{Namespace}.{Name}";
    public List<PropertyInfo> Properties { get; }

    public ClassInfo(string @namespace, string name, List<PropertyInfo> properties)
    {
        Namespace = @namespace;
        Name = name;
        Properties = properties;
    }
}

/// <summary>
/// 属性信息
/// </summary>
public class PropertyInfo
{
    public string Name { get; }
    public string Type { get; }

    public PropertyInfo(string name, string type)
    {
        Name = name;
        Type = type;
    }
}