using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TinyDb.SourceGenerator;

public partial class TinyDbSourceGenerator
{
    /// <summary>
    /// 生成AOT静态帮助器类
    /// </summary>
    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var sb = new StringBuilder();

        // 添加文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using TinyDb.Bson;");
        sb.AppendLine("using TinyDb.Serialization;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");

        // 添加实体类的命名空间引用
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"using {classInfo.Namespace};");
        }
        sb.AppendLine();

        // 添加命名空间
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"namespace {classInfo.Namespace}");
            sb.AppendLine("{");
        }

        // 添加静态帮助器类
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {classInfo.FullyQualifiedTypeReference} 的AOT支持帮助器（源代码生成器生成）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    internal static class {classInfo.HelperClassName}{classInfo.TypeParameterList}");
        if (!string.IsNullOrEmpty(classInfo.TypeParameterConstraints))
        {
            sb.AppendLine($"        {classInfo.TypeParameterConstraints}");
        }
        sb.AppendLine("    {");

        // 生成AOT兼容的ID访问方法
        if (classInfo.IdProperty != null)
        {
            var idProp = classInfo.IdProperty;
            var idAccess = idProp.AccessName;
            var normalizedIdType = NormalizeTypeName(idProp.NonNullableType);
            var isObjectId = normalizedIdType.EndsWith("ObjectId", StringComparison.Ordinal);

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 获取实体的ID值（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <returns>ID值</returns>");
            sb.AppendLine($"        public static BsonValue GetId({classInfo.FullyQualifiedTypeReference} entity)");
            sb.AppendLine("        {");
            if (!classInfo.IsValueType)
            {
                sb.AppendLine($"            if (entity == null) return BsonNull.Value;");
            }
            sb.AppendLine($"            // 硬编码ID属性访问 - 避免AOT反射问题");

            if (isObjectId)
            {
                if (idProp.IsNullableValueType)
                {
                    sb.AppendLine($"            return entity.{idAccess}.HasValue ? new BsonObjectId(entity.{idAccess}.Value) : BsonNull.Value;");
                }
                else
                {
                    sb.AppendLine($"            return new BsonObjectId(entity.{idAccess});");
                }
            }
            else if (string.Equals(normalizedIdType, "string", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"            return new BsonString(entity.{idAccess} ?? \"\");");
            }
            else if (string.Equals(normalizedIdType, "int", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"            return new BsonInt32(entity.{idAccess});");
            }
            else if (string.Equals(normalizedIdType, "long", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"            return new BsonInt64(entity.{idAccess});");
            }
            else
            {
                // 对于其他类型，使用BsonConversion辅助方法
                sb.AppendLine($"            return TinyDb.Serialization.BsonConversion.ConvertToBsonValue(entity.{idAccess});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 设置实体的ID值（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <param name=\"id\">ID值</param>");
            var setIdEntityParameter = classInfo.IsValueType
                ? $"ref {classInfo.FullyQualifiedTypeReference} entity"
                : $"{classInfo.FullyQualifiedTypeReference} entity";
            sb.AppendLine($"        public static void SetId({setIdEntityParameter}, BsonValue id)");
            sb.AppendLine("        {");
            if (!classInfo.IsValueType)
            {
                sb.AppendLine($"            if (entity == null || id?.IsNull != false) return;");
            }
            else
            {
                sb.AppendLine($"            if (id?.IsNull != false) return;");
            }

            if (!idProp.CanSet)
            {
                sb.AppendLine("            return;");
            }
            else if (isObjectId)
            {
                sb.AppendLine("            if (id is BsonObjectId bsonObjectId)");
                sb.AppendLine($"                entity.{idAccess} = bsonObjectId.Value;");
                sb.AppendLine("            else if (id is BsonString bsonString && ObjectId.TryParse(bsonString.Value, out var parsedObjectId))");
                sb.AppendLine($"                entity.{idAccess} = parsedObjectId;");
            }
            else if (string.Equals(normalizedIdType, "string", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine("            if (id is BsonString bsonString)");
                sb.AppendLine($"                entity.{idAccess} = bsonString.Value ?? \"\";");
                sb.AppendLine("            else if (id != null && !id.IsNull)");
                sb.AppendLine($"                entity.{idAccess} = id.ToString();");
            }
            else if (string.Equals(normalizedIdType, "int", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine("            if (id is BsonInt32 bsonInt32)");
                sb.AppendLine($"                entity.{idAccess} = bsonInt32.Value;");
            }
            else if (string.Equals(normalizedIdType, "long", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine("            if (id is BsonInt64 bsonInt64)");
                sb.AppendLine($"                entity.{idAccess} = bsonInt64.Value;");
            }
            else if (string.Equals(normalizedIdType, "Guid", StringComparison.Ordinal))
            {
                sb.AppendLine("            if (id is BsonBinary bsonBinary)");
                sb.AppendLine($"                entity.{idAccess} = new Guid(bsonBinary.Bytes);");
                sb.AppendLine("            else if (id is BsonString bsonGuidString && Guid.TryParse(bsonGuidString.Value, out var parsedGuid))");
                sb.AppendLine($"                entity.{idAccess} = parsedGuid;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 检查实体是否有有效的ID（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <returns>是否有有效ID</returns>");
            sb.AppendLine($"        public static bool HasValidId({classInfo.FullyQualifiedTypeReference} entity)");
            sb.AppendLine("        {");
            if (!classInfo.IsValueType)
            {
                sb.AppendLine($"            if (entity == null) return false;");
            }
            sb.AppendLine($"            // 硬编码ID属性验证 - 避免AOT反射问题");

            if (isObjectId)
            {
                sb.AppendLine($"            return entity.{idAccess} != ObjectId.Empty;");
            }
            else
            {
                if (string.Equals(normalizedIdType, "string", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"            return !string.IsNullOrWhiteSpace(entity.{idAccess});");
                }
                else if (string.Equals(normalizedIdType, "Guid", StringComparison.Ordinal))
                {
                    if (idProp.IsNullableValueType)
                    {
                        sb.AppendLine($"            return entity.{idAccess}.HasValue && entity.{idAccess}.Value != Guid.Empty;");
                    }
                    else
                    {
                        sb.AppendLine($"            return entity.{idAccess} != Guid.Empty;");
                    }
                }
                else if (idProp.IsNullableValueType)
                {
                    sb.AppendLine($"            return entity.{idAccess}.HasValue && !System.Collections.Generic.EqualityComparer<{idProp.FullyQualifiedNonNullableType}>.Default.Equals(entity.{idAccess}.Value, default);");
                }
                else if (idProp.IsValueType)
                {
                    sb.AppendLine($"            return !System.Collections.Generic.EqualityComparer<{idProp.FullyQualifiedNonNullableType}>.Default.Equals(entity.{idAccess}, default);");
                }
                else
                {
                    sb.AppendLine($"            return entity.{idAccess} != null;");
                }
            }

            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 获取实体的ID值（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <returns>ID值</returns>");
            sb.AppendLine($"        public static BsonValue GetId({classInfo.FullyQualifiedTypeReference} entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 没有找到ID属性");
            sb.AppendLine("            return BsonNull.Value;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 设置实体的ID值（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <param name=\"id\">ID值</param>");
            var setIdEntityParameter = classInfo.IsValueType
                ? $"ref {classInfo.FullyQualifiedTypeReference} entity"
                : $"{classInfo.FullyQualifiedTypeReference} entity";
            sb.AppendLine($"        public static void SetId({setIdEntityParameter}, BsonValue id)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 没有找到ID属性，忽略设置");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 检查实体是否有有效的ID（AOT兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
            sb.AppendLine("        /// <returns>是否有有效ID</returns>");
            sb.AppendLine($"        public static bool HasValidId({classInfo.FullyQualifiedTypeReference} entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 没有找到ID属性");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
        }

        AppendIdAdapterMetadata(sb, classInfo);

        // 生成完整的序列化方法
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 将实体序列化为BSON文档（AOT兼容）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
        sb.AppendLine("        /// <returns>BSON文档</returns>");
        sb.AppendLine($"        public static BsonDocument ToDocument({classInfo.FullyQualifiedTypeReference} entity)");
        sb.AppendLine("        {");
        if (!classInfo.IsValueType)
        {
            sb.AppendLine("            if (entity == null) throw new ArgumentNullException(nameof(entity));");
        }
        sb.AppendLine("            var documentBuilder = new BsonDocumentBuilder();");
        sb.AppendLine();

        // 为每个属性生成序列化代码
        var constructorPropertyNames = new HashSet<string>(
            classInfo.ConstructorParameters.Select(static p => p.Property.Name),
            StringComparer.Ordinal);
        foreach (var prop in classInfo.Properties.Where(p => !p.HasIgnoreAttribute))
        {
            var bsonCode = RewriteDocumentSetToBuilder(SourceGeneratorHelpers.GeneratePropertySerialization(prop));
            sb.AppendLine($"            // 序列化属性: {prop.Name}");
            sb.AppendLine(bsonCode);
            sb.AppendLine();
        }

        // 确保包含集合名称字段
        sb.AppendLine("            // 确保包含集合名称字段");
        sb.AppendLine("            if (!documentBuilder.ContainsKey(\"_collection\"))");
        sb.AppendLine("            {");
        sb.AppendLine($"                documentBuilder.Set(\"_collection\", {ToCSharpStringLiteral(classInfo.CollectionName ?? classInfo.Name)});");
        sb.AppendLine("            }");

        sb.AppendLine("            return documentBuilder.Build();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成反序列化方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 从BSON文档反序列化实体（AOT兼容）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"document\">BSON文档</param>");
        sb.AppendLine("        /// <returns>实体实例</returns>");
        sb.AppendLine($"        public static {classInfo.FullyQualifiedTypeReference} FromDocument(BsonDocument document)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (document == null) throw new ArgumentNullException(nameof(document));");
        if (classInfo.ConstructorParameters.Count > 0)
        {
            foreach (var parameter in classInfo.ConstructorParameters)
            {
                var prop = parameter.Property;
                var bsonFieldName = GetBsonFieldName(prop);
                var localName = $"ctor_{prop.Name}";
                var bsonLocalName = $"bsonCtor_{prop.Name}";
                sb.AppendLine($"            {prop.FullyQualifiedType} {localName} = document.TryGetValue(\"{bsonFieldName}\", out var {bsonLocalName})");
                sb.AppendLine($"                ? ConvertFromBsonValue<{prop.FullyQualifiedType}>({bsonLocalName})!");
                sb.AppendLine("                : default!;");
            }

            var arguments = string.Join(", ", classInfo.ConstructorParameters.Select(p => $"ctor_{p.Property.Name}"));
            sb.AppendLine($"            var entity = new {classInfo.FullyQualifiedTypeReference}({arguments});");
        }
        else
        {
            sb.AppendLine($"            var entity = new {classInfo.FullyQualifiedTypeReference}();");
        }
        sb.AppendLine();

        // 为每个属性生成反序列化代码
        foreach (var prop in classInfo.Properties.Where(p => !p.HasIgnoreAttribute && p.CanSet && !constructorPropertyNames.Contains(p.Name)))
        {
            var bsonCode = SourceGeneratorHelpers.GeneratePropertyDeserialization(prop);
            sb.AppendLine($"            // 反序列化属性: {prop.Name}");
            sb.AppendLine(bsonCode);
            sb.AppendLine();
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
        sb.AppendLine();
        AppendBsonConversionHelpers(sb, classInfo);

        // 生成属性访问方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取属性值（AOT兼容）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"entity\">实体实例</param>");
        sb.AppendLine("        /// <param name=\"propertyName\">属性名称</param>");
        sb.AppendLine("        /// <returns>属性值</returns>");
        sb.AppendLine($"        public static object? GetPropertyValue({classInfo.FullyQualifiedTypeReference} entity, string propertyName)");
        sb.AppendLine("        {");
        if (!classInfo.IsValueType)
        {
            sb.AppendLine("            if (entity == null) throw new ArgumentNullException(nameof(entity));");
        }
        sb.AppendLine("            return propertyName switch");
        sb.AppendLine("            {");

        foreach (var prop in classInfo.Properties.Where(p => !p.HasIgnoreAttribute))
        {
            sb.AppendLine($"                \"{prop.Name}\" => entity.{prop.AccessName},");
        }

        sb.AppendLine("                _ => null");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        var trySetEntityParameter = classInfo.IsValueType
            ? $"ref {classInfo.FullyQualifiedTypeReference} entity"
            : $"{classInfo.FullyQualifiedTypeReference} entity";
        sb.AppendLine("        public static bool TrySetPropertyValue(" + trySetEntityParameter + ", string propertyName, object? value)");
        sb.AppendLine("        {");
        if (!classInfo.IsValueType)
        {
            sb.AppendLine("            if (entity == null) throw new ArgumentNullException(nameof(entity));");
        }
        sb.AppendLine("            switch (propertyName)");
        sb.AppendLine("            {");

        foreach (var prop in classInfo.Properties.Where(p => !p.HasIgnoreAttribute && p.CanSet))
        {
            sb.AppendLine($"                case \"{prop.Name}\":");
            sb.AppendLine($"                    entity.{prop.AccessName} = value is null ? default! : ({prop.FullyQualifiedType})value;");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        GenerateForeignKeyReferences(sb, classInfo);

        sb.AppendLine("    }");

        // 关闭命名空间
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string RewriteDocumentSetToBuilder(string source)
    {
        return source.Replace("document = document.Set(", "documentBuilder.Set(");
    }

    private static string GetBsonFieldName(PropertyInfo prop)
    {
        return prop.IsId ? "_id" : SourceGeneratorFieldName.ToCamelCase(prop.Name);
    }

}
