using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace TinyDb.SourceGenerator;

public partial class TinyDbSourceGenerator
{

    /// <summary>
    /// 生成注册所有AOT辅助适配器的聚合类
    /// </summary>
    private static string GenerateRegistrySource(IReadOnlyCollection<ClassInfo> classes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace TinyDb.Serialization;");
        sb.AppendLine();
        sb.AppendLine("internal static class AotHelperRegistryModule");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        foreach (var classInfo in classes)
        {
            if (classInfo.IsGenericType)
            {
                continue;
            }

            // 使用完整命名空间加帮助器类名
            var helperFullName = string.IsNullOrEmpty(classInfo.Namespace)
                ? classInfo.HelperClassName
                : $"{classInfo.Namespace}.{classInfo.HelperClassName}";
            var setIdAction = classInfo.IsValueType
                ? "            static (_, _) => { },"
                : $"            (entity, id) => {helperFullName}.SetId(entity, id),";
            var trySetPropertyAction = classInfo.IsValueType
                ? "            static (_, _, _) => false,"
                : $"            (entity, propertyName, value) => {helperFullName}.TrySetPropertyValue(entity, propertyName, value),";
            var generateIdAction = classInfo.IsValueType
                ? "            static _ => false,"
                : $"            entity => {helperFullName}.GenerateIdIfNeeded(entity),";
            var setIdByRefAction = classInfo.IsValueType
                ? $"            (ref {classInfo.FullyQualifiedTypeReference} entity, global::TinyDb.Bson.BsonValue id) => {helperFullName}.SetId(ref entity, id),"
                : $"            (ref {classInfo.FullyQualifiedTypeReference} entity, global::TinyDb.Bson.BsonValue id) => {helperFullName}.SetId(entity, id),";
            var trySetPropertyByRefAction = classInfo.IsValueType
                ? $"            (ref {classInfo.FullyQualifiedTypeReference} entity, string propertyName, object? value) => {helperFullName}.TrySetPropertyValue(ref entity, propertyName, value),"
                : $"            (ref {classInfo.FullyQualifiedTypeReference} entity, string propertyName, object? value) => {helperFullName}.TrySetPropertyValue(entity, propertyName, value),";
            var generateIdByRefAction = classInfo.IsValueType
                ? $"            (ref {classInfo.FullyQualifiedTypeReference} entity) => {helperFullName}.GenerateIdIfNeeded(ref entity))"
                : $"            (ref {classInfo.FullyQualifiedTypeReference} entity) => {helperFullName}.GenerateIdIfNeeded(entity))";

            sb.AppendLine($"        AotHelperRegistry.Register(new AotEntityAdapter<{classInfo.FullyQualifiedTypeReference}>(");
            sb.AppendLine($"            entity => {helperFullName}.ToDocument(entity),");
            sb.AppendLine($"            document => {helperFullName}.FromDocument(document),");
            sb.AppendLine($"            entity => {helperFullName}.GetId(entity),");
            sb.AppendLine(setIdAction);
            sb.AppendLine($"            entity => {helperFullName}.HasValidId(entity),");
            sb.AppendLine($"            (entity, propertyName) => {helperFullName}.GetPropertyValue(entity, propertyName),");
            sb.AppendLine(trySetPropertyAction);
            sb.AppendLine($"            {helperFullName}.ForeignKeyReferences,");
            sb.AppendLine($"            {helperFullName}.IdPropertyName,");
            sb.AppendLine($"            {helperFullName}.IdPropertyType,");
            sb.AppendLine($"            {helperFullName}.IdGenerationStrategy,");
            sb.AppendLine($"            {helperFullName}.IdGenerationSequenceName,");
            sb.AppendLine(generateIdAction);
            sb.AppendLine(setIdByRefAction);
            sb.AppendLine(trySetPropertyByRefAction);
            sb.AppendLine(generateIdByRefAction + ");");
            AppendMetadataRegistryRegistration(sb, classInfo);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }


    private static void AppendMetadataRegistryRegistration(StringBuilder sb, ClassInfo classInfo)
    {
        sb.AppendLine($"        global::TinyDb.Metadata.MetadataRegistry.Register(typeof({classInfo.FullyQualifiedTypeReference}), new global::TinyDb.Metadata.EntityMetadata");
        sb.AppendLine("        {");
        sb.AppendLine($"            TypeName = {ToCSharpStringLiteral(classInfo.RuntimeFullName)},");
        sb.AppendLine($"            CollectionName = {ToCSharpStringLiteral(classInfo.CollectionName ?? classInfo.Name)},");
        sb.AppendLine($"            DisplayName = {ToCSharpStringLiteral(classInfo.DisplayName)},");
        sb.AppendLine($"            Description = {ToCSharpStringLiteral(classInfo.Description)},");
        sb.AppendLine("            Properties = new List<global::TinyDb.Metadata.PropertyMetadata>");
        sb.AppendLine("            {");

        foreach (var property in classInfo.Properties.Where(static p => !p.HasIgnoreAttribute))
        {
            sb.AppendLine("                new global::TinyDb.Metadata.PropertyMetadata");
            sb.AppendLine("                {");
            sb.AppendLine($"                    PropertyName = {ToCSharpStringLiteral(property.Name)},");
            sb.AppendLine($"                    PropertyType = {ToCSharpStringLiteral(property.MetadataTypeName)},");
            sb.AppendLine($"                    DisplayName = {ToCSharpStringLiteral(property.DisplayName)},");
            sb.AppendLine($"                    Description = {ToCSharpStringLiteral(property.Description)},");
            sb.AppendLine($"                    Order = {property.Order},");
            sb.AppendLine($"                    Required = {(property.Required ? "true" : "false")},");
            sb.AppendLine($"                    IsPrimaryKey = {(property.IsId ? "true" : "false")},");
            sb.AppendLine($"                    ForeignKeyCollection = {ToCSharpStringLiteral(property.ForeignKeyCollectionName)}");
            sb.AppendLine("                },");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        });");
    }

    /// <summary>
    /// 生成映射器类
    /// </summary>

}
